- name: Clone repository
  become: yes
  become_user: "{{crimestats_app_user}}"
  git: dest={{crimestats_app_root}}
       repo=git://github.com/travishathaway/crimestats.git
       accept_hostkey=yes

- name: Install gunicorn
  command: "{{crimestats_bin}}/conda install gunicorn -y"

- name: Install conda dependencies
  command: "{{crimestats_bin}}/conda install --file {{crimestats_app_root}}conda_requirements.txt -y"

- name: Install dependencies
  pip: executable={{crimestats_bin}}/pip
       requirements={{crimestats_app_root}}requirements.txt

- name: Ensure doc root exists
  become: yes
  become_method: sudo
  file: >
    path={{crimestats_app_doc_root}} owner={{ansible_ssh_user}}
    group={{ansible_ssh_user}} state=directory

- name: Copy systemd service config
  become: yes
  become_method: sudo
  template: src=crimestats.service dest=/lib/systemd/system/crimestats.service

- name: Make symlink for service file
  become: yes
  become_method: sudo
  file: >
      src=/lib/systemd/system/crimestats.service 
      dest=/etc/systemd/system/multi-user.target.wants/crimestats.service state=link

- name: Copy systemd socket config
  become: yes
  become_method: sudo
  template: src=crimestats.socket dest=/lib/systemd/system/crimestats.socket

- name: Make symlink for socket file
  become: yes
  become_method: sudo
  file: > 
      src=/lib/systemd/system/crimestats.socket 
      dest=/etc/systemd/system/multi-user.target.wants/crimestats.socket state=link

- name: Copy gunicorn ini
  become: yes
  become_user: "{{crimestats_app_user}}"
  template: src=crimestats.ini 
            dest={{crimestats_app_root}}crimestats.ini

- name: Start crimestats service
  become: yes
  become_method: sudo
  systemd: name=crimestats state=restarted daemon_reload=yes
