---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/main.yml
    - group_vars/private.yml

  tasks:
    - name: Provision a set of instances
      ec2:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        key_name: "{{aws_ssh_key}}"
        group: "{{aws_security_group}}"
        instance_type: t2.micro
        image: "{{aws_ami}}"
        region: "{{aws_region}}"
        wait: true
        exact_count: 1
        count_tag:
          name: webserver
        instance_tags:
          Name: webserver
          type: webserver
          public_facing: 'yes'
      register: ec2

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: '{{ec2.instances}}'

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=5 timeout=60 state=started
      with_items: '{{ec2.instances}}'

- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/main.yml
    - group_vars/private.yml

  tasks:
    - name: Associate Elastic IP
      ec2_eip:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        device_id: "{{ item.id }}"
        ip: "{{aws_elastic_ip}}"
        region: "{{aws_region}}"
      with_items: '{{ec2.instances}}'
