static:
	ansible-playbook static.yml -i hosts --ask-become-pass
cs:
	ansible-playbook crimestats.yml -i hosts
om:
	ansible-playbook oregon_measures.yml -i hosts
nginx:
	ansible-playbook nginx.yml -i hosts
postgresql:
	ansible-playbook postgresql.yml -i hosts
