---
- hosts: "localhost"
  vars_files:
    - group_vars/main.yml
  vars:
    build_static_repo_url: https://github.com/travishathaway/crimestats.git
    build_static_repo_branch: master
  roles:
    - role: build_static
